// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DigitalProviderUIClient is the client API for DigitalProviderUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DigitalProviderUIClient interface {
	// ListEngineSpecs returns a list of Provider Engine(s) that can be started through the Digital Provider UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (DigitalProviderUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the Digital Provider UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type digitalProviderUIClient struct {
	cc grpc.ClientConnInterface
}

func NewDigitalProviderUIClient(cc grpc.ClientConnInterface) DigitalProviderUIClient {
	return &digitalProviderUIClient{cc}
}

func (c *digitalProviderUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (DigitalProviderUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &DigitalProviderUI_ServiceDesc.Streams[0], "/v1.DigitalProviderUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &digitalProviderUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DigitalProviderUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type digitalProviderUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *digitalProviderUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *digitalProviderUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.DigitalProviderUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DigitalProviderUIServer is the server API for DigitalProviderUI service.
// All implementations must embed UnimplementedDigitalProviderUIServer
// for forward compatibility
type DigitalProviderUIServer interface {
	// ListEngineSpecs returns a list of Provider Engine(s) that can be started through the Digital Provider UI.
	ListEngineSpecs(*ListEngineSpecsRequest, DigitalProviderUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the Digital Provider UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedDigitalProviderUIServer()
}

// UnimplementedDigitalProviderUIServer must be embedded to have forward compatible implementations.
type UnimplementedDigitalProviderUIServer struct {
}

func (UnimplementedDigitalProviderUIServer) ListEngineSpecs(*ListEngineSpecsRequest, DigitalProviderUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedDigitalProviderUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedDigitalProviderUIServer) mustEmbedUnimplementedDigitalProviderUIServer() {}

// UnsafeDigitalProviderUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DigitalProviderUIServer will
// result in compilation errors.
type UnsafeDigitalProviderUIServer interface {
	mustEmbedUnimplementedDigitalProviderUIServer()
}

func RegisterDigitalProviderUIServer(s grpc.ServiceRegistrar, srv DigitalProviderUIServer) {
	s.RegisterService(&DigitalProviderUI_ServiceDesc, srv)
}

func _DigitalProviderUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DigitalProviderUIServer).ListEngineSpecs(m, &digitalProviderUIListEngineSpecsServer{stream})
}

type DigitalProviderUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type digitalProviderUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *digitalProviderUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _DigitalProviderUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DigitalProviderUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.DigitalProviderUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DigitalProviderUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DigitalProviderUI_ServiceDesc is the grpc.ServiceDesc for DigitalProviderUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DigitalProviderUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.DigitalProviderUI",
	HandlerType: (*DigitalProviderUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _DigitalProviderUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _DigitalProviderUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "provider-ui.proto",
}
