// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DigitalProviderClient is the client API for DigitalProvider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DigitalProviderClient interface {
	// StartLocalEngine starts a Provider Engine on the Bhojpur.NET Platform directly.
	// The incoming requests are expected in the following order:
	//   1. metadata
	//   2. all bytes constituting the provider/config.yaml
	//   3. all bytes constituting the Provider Engine YAML that will be executed (that the config.yaml points to)
	//   4. all bytes constituting the gzipped Bhojpur.NET Platform application tar stream
	//   5. the Bhojpur.NET Platform application tar stream done marker
	StartLocalEngine(ctx context.Context, opts ...grpc.CallOption) (DigitalProvider_StartLocalEngineClient, error)
	// StartFromPreviousEngine starts a new Provider Engine based on a previous one.
	// If the previous Provider Engine does not have the can-replay condition set this call will result in an error.
	StartFromPreviousEngine(ctx context.Context, in *StartFromPreviousEngineRequest, opts ...grpc.CallOption) (*StartEngineResponse, error)
	// StartEngineRequest starts a new Provider Engine based on its specification.
	StartEngine(ctx context.Context, in *StartEngineRequest, opts ...grpc.CallOption) (*StartEngineResponse, error)
	// Searches for Provider Engine(s) known to this Provider Engine
	ListEngines(ctx context.Context, in *ListEnginesRequest, opts ...grpc.CallOption) (*ListEnginesResponse, error)
	// Subscribe listens to new Provider Engine(s) updates
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (DigitalProvider_SubscribeClient, error)
	// GetEngine retrieves details of a single Provider Engine
	GetEngine(ctx context.Context, in *GetEngineRequest, opts ...grpc.CallOption) (*GetEngineResponse, error)
	// Listen listens to Provider Engine updates and log output of a running Engine
	Listen(ctx context.Context, in *ListenRequest, opts ...grpc.CallOption) (DigitalProvider_ListenClient, error)
	// StopEngine stops a currently running Provider Engine
	StopEngine(ctx context.Context, in *StopEngineRequest, opts ...grpc.CallOption) (*StopEngineResponse, error)
}

type digitalProviderClient struct {
	cc grpc.ClientConnInterface
}

func NewDigitalProviderClient(cc grpc.ClientConnInterface) DigitalProviderClient {
	return &digitalProviderClient{cc}
}

func (c *digitalProviderClient) StartLocalEngine(ctx context.Context, opts ...grpc.CallOption) (DigitalProvider_StartLocalEngineClient, error) {
	stream, err := c.cc.NewStream(ctx, &DigitalProvider_ServiceDesc.Streams[0], "/v1.DigitalProvider/StartLocalEngine", opts...)
	if err != nil {
		return nil, err
	}
	x := &digitalProviderStartLocalEngineClient{stream}
	return x, nil
}

type DigitalProvider_StartLocalEngineClient interface {
	Send(*StartLocalEngineRequest) error
	CloseAndRecv() (*StartEngineResponse, error)
	grpc.ClientStream
}

type digitalProviderStartLocalEngineClient struct {
	grpc.ClientStream
}

func (x *digitalProviderStartLocalEngineClient) Send(m *StartLocalEngineRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *digitalProviderStartLocalEngineClient) CloseAndRecv() (*StartEngineResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(StartEngineResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *digitalProviderClient) StartFromPreviousEngine(ctx context.Context, in *StartFromPreviousEngineRequest, opts ...grpc.CallOption) (*StartEngineResponse, error) {
	out := new(StartEngineResponse)
	err := c.cc.Invoke(ctx, "/v1.DigitalProvider/StartFromPreviousEngine", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *digitalProviderClient) StartEngine(ctx context.Context, in *StartEngineRequest, opts ...grpc.CallOption) (*StartEngineResponse, error) {
	out := new(StartEngineResponse)
	err := c.cc.Invoke(ctx, "/v1.DigitalProvider/StartEngine", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *digitalProviderClient) ListEngines(ctx context.Context, in *ListEnginesRequest, opts ...grpc.CallOption) (*ListEnginesResponse, error) {
	out := new(ListEnginesResponse)
	err := c.cc.Invoke(ctx, "/v1.DigitalProvider/ListEngines", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *digitalProviderClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (DigitalProvider_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &DigitalProvider_ServiceDesc.Streams[1], "/v1.DigitalProvider/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &digitalProviderSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DigitalProvider_SubscribeClient interface {
	Recv() (*SubscribeResponse, error)
	grpc.ClientStream
}

type digitalProviderSubscribeClient struct {
	grpc.ClientStream
}

func (x *digitalProviderSubscribeClient) Recv() (*SubscribeResponse, error) {
	m := new(SubscribeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *digitalProviderClient) GetEngine(ctx context.Context, in *GetEngineRequest, opts ...grpc.CallOption) (*GetEngineResponse, error) {
	out := new(GetEngineResponse)
	err := c.cc.Invoke(ctx, "/v1.DigitalProvider/GetEngine", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *digitalProviderClient) Listen(ctx context.Context, in *ListenRequest, opts ...grpc.CallOption) (DigitalProvider_ListenClient, error) {
	stream, err := c.cc.NewStream(ctx, &DigitalProvider_ServiceDesc.Streams[2], "/v1.DigitalProvider/Listen", opts...)
	if err != nil {
		return nil, err
	}
	x := &digitalProviderListenClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DigitalProvider_ListenClient interface {
	Recv() (*ListenResponse, error)
	grpc.ClientStream
}

type digitalProviderListenClient struct {
	grpc.ClientStream
}

func (x *digitalProviderListenClient) Recv() (*ListenResponse, error) {
	m := new(ListenResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *digitalProviderClient) StopEngine(ctx context.Context, in *StopEngineRequest, opts ...grpc.CallOption) (*StopEngineResponse, error) {
	out := new(StopEngineResponse)
	err := c.cc.Invoke(ctx, "/v1.DigitalProvider/StopEngine", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DigitalProviderServer is the server API for DigitalProvider service.
// All implementations must embed UnimplementedDigitalProviderServer
// for forward compatibility
type DigitalProviderServer interface {
	// StartLocalEngine starts a Provider Engine on the Bhojpur.NET Platform directly.
	// The incoming requests are expected in the following order:
	//   1. metadata
	//   2. all bytes constituting the provider/config.yaml
	//   3. all bytes constituting the Provider Engine YAML that will be executed (that the config.yaml points to)
	//   4. all bytes constituting the gzipped Bhojpur.NET Platform application tar stream
	//   5. the Bhojpur.NET Platform application tar stream done marker
	StartLocalEngine(DigitalProvider_StartLocalEngineServer) error
	// StartFromPreviousEngine starts a new Provider Engine based on a previous one.
	// If the previous Provider Engine does not have the can-replay condition set this call will result in an error.
	StartFromPreviousEngine(context.Context, *StartFromPreviousEngineRequest) (*StartEngineResponse, error)
	// StartEngineRequest starts a new Provider Engine based on its specification.
	StartEngine(context.Context, *StartEngineRequest) (*StartEngineResponse, error)
	// Searches for Provider Engine(s) known to this Provider Engine
	ListEngines(context.Context, *ListEnginesRequest) (*ListEnginesResponse, error)
	// Subscribe listens to new Provider Engine(s) updates
	Subscribe(*SubscribeRequest, DigitalProvider_SubscribeServer) error
	// GetEngine retrieves details of a single Provider Engine
	GetEngine(context.Context, *GetEngineRequest) (*GetEngineResponse, error)
	// Listen listens to Provider Engine updates and log output of a running Engine
	Listen(*ListenRequest, DigitalProvider_ListenServer) error
	// StopEngine stops a currently running Provider Engine
	StopEngine(context.Context, *StopEngineRequest) (*StopEngineResponse, error)
	mustEmbedUnimplementedDigitalProviderServer()
}

// UnimplementedDigitalProviderServer must be embedded to have forward compatible implementations.
type UnimplementedDigitalProviderServer struct {
}

func (UnimplementedDigitalProviderServer) StartLocalEngine(DigitalProvider_StartLocalEngineServer) error {
	return status.Errorf(codes.Unimplemented, "method StartLocalEngine not implemented")
}
func (UnimplementedDigitalProviderServer) StartFromPreviousEngine(context.Context, *StartFromPreviousEngineRequest) (*StartEngineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartFromPreviousEngine not implemented")
}
func (UnimplementedDigitalProviderServer) StartEngine(context.Context, *StartEngineRequest) (*StartEngineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartEngine not implemented")
}
func (UnimplementedDigitalProviderServer) ListEngines(context.Context, *ListEnginesRequest) (*ListEnginesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEngines not implemented")
}
func (UnimplementedDigitalProviderServer) Subscribe(*SubscribeRequest, DigitalProvider_SubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedDigitalProviderServer) GetEngine(context.Context, *GetEngineRequest) (*GetEngineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEngine not implemented")
}
func (UnimplementedDigitalProviderServer) Listen(*ListenRequest, DigitalProvider_ListenServer) error {
	return status.Errorf(codes.Unimplemented, "method Listen not implemented")
}
func (UnimplementedDigitalProviderServer) StopEngine(context.Context, *StopEngineRequest) (*StopEngineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopEngine not implemented")
}
func (UnimplementedDigitalProviderServer) mustEmbedUnimplementedDigitalProviderServer() {}

// UnsafeDigitalProviderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DigitalProviderServer will
// result in compilation errors.
type UnsafeDigitalProviderServer interface {
	mustEmbedUnimplementedDigitalProviderServer()
}

func RegisterDigitalProviderServer(s grpc.ServiceRegistrar, srv DigitalProviderServer) {
	s.RegisterService(&DigitalProvider_ServiceDesc, srv)
}

func _DigitalProvider_StartLocalEngine_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DigitalProviderServer).StartLocalEngine(&digitalProviderStartLocalEngineServer{stream})
}

type DigitalProvider_StartLocalEngineServer interface {
	SendAndClose(*StartEngineResponse) error
	Recv() (*StartLocalEngineRequest, error)
	grpc.ServerStream
}

type digitalProviderStartLocalEngineServer struct {
	grpc.ServerStream
}

func (x *digitalProviderStartLocalEngineServer) SendAndClose(m *StartEngineResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *digitalProviderStartLocalEngineServer) Recv() (*StartLocalEngineRequest, error) {
	m := new(StartLocalEngineRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _DigitalProvider_StartFromPreviousEngine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartFromPreviousEngineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DigitalProviderServer).StartFromPreviousEngine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.DigitalProvider/StartFromPreviousEngine",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DigitalProviderServer).StartFromPreviousEngine(ctx, req.(*StartFromPreviousEngineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DigitalProvider_StartEngine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartEngineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DigitalProviderServer).StartEngine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.DigitalProvider/StartEngine",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DigitalProviderServer).StartEngine(ctx, req.(*StartEngineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DigitalProvider_ListEngines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEnginesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DigitalProviderServer).ListEngines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.DigitalProvider/ListEngines",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DigitalProviderServer).ListEngines(ctx, req.(*ListEnginesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DigitalProvider_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DigitalProviderServer).Subscribe(m, &digitalProviderSubscribeServer{stream})
}

type DigitalProvider_SubscribeServer interface {
	Send(*SubscribeResponse) error
	grpc.ServerStream
}

type digitalProviderSubscribeServer struct {
	grpc.ServerStream
}

func (x *digitalProviderSubscribeServer) Send(m *SubscribeResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _DigitalProvider_GetEngine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEngineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DigitalProviderServer).GetEngine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.DigitalProvider/GetEngine",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DigitalProviderServer).GetEngine(ctx, req.(*GetEngineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DigitalProvider_Listen_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListenRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DigitalProviderServer).Listen(m, &digitalProviderListenServer{stream})
}

type DigitalProvider_ListenServer interface {
	Send(*ListenResponse) error
	grpc.ServerStream
}

type digitalProviderListenServer struct {
	grpc.ServerStream
}

func (x *digitalProviderListenServer) Send(m *ListenResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _DigitalProvider_StopEngine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopEngineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DigitalProviderServer).StopEngine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.DigitalProvider/StopEngine",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DigitalProviderServer).StopEngine(ctx, req.(*StopEngineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DigitalProvider_ServiceDesc is the grpc.ServiceDesc for DigitalProvider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DigitalProvider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.DigitalProvider",
	HandlerType: (*DigitalProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartFromPreviousEngine",
			Handler:    _DigitalProvider_StartFromPreviousEngine_Handler,
		},
		{
			MethodName: "StartEngine",
			Handler:    _DigitalProvider_StartEngine_Handler,
		},
		{
			MethodName: "ListEngines",
			Handler:    _DigitalProvider_ListEngines_Handler,
		},
		{
			MethodName: "GetEngine",
			Handler:    _DigitalProvider_GetEngine_Handler,
		},
		{
			MethodName: "StopEngine",
			Handler:    _DigitalProvider_StopEngine_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StartLocalEngine",
			Handler:       _DigitalProvider_StartLocalEngine_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Subscribe",
			Handler:       _DigitalProvider_Subscribe_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Listen",
			Handler:       _DigitalProvider_Listen_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "provider.proto",
}
